apiVersion: v1
kind: Secret
metadata:
  name: argocd-manager-token
  namespace: aniketdevops
  annotations:
    kubernetes.io/service-account.name: argocd-manager
type: kubernetes.io/service-account-token
