apiVersion: apps/v1
kind: Deployment
metadata:
  name: aniketdevops
  namespace: aniketdevops
  labels:
    app: aniketdevops
spec:
  nodeSelector:
    workload: webapp
  replicas: 3  # Number of pod replicas
  selector:
    matchLabels:
      app: aniketdevops
  template:
    metadata:
      labels:
        app: aniketdevops
    spec:
      containers:
      - name: aniketdevops
        image: adevopsacr.azurecr.io/aniketdevops:latest  # Use the latest image from ACR
        imagePullPolicy: Always
        ports:
        - containerPort: 80
