apiVersion: apps/v1
kind: Deployment
metadata:
  name: aniketdevops
  namespace: aniketdevops
  labels:
    app: aniketdevops
spec:
  nodeSelector:
    workload: webapp
  selector:
    matchLabels:
      app: aniketdevops
  template:
    metadata:
      labels:
        app: aniketdevops
    spec:
      containers:
      - name: aniketdevops
        image: aniketkumarsinha/aniketdevops:latest  
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
