apiVersion: v1
kind: Secret
metadata:
  name: ${NAME}
  namespace: ${NAMESPACE}
  labels:
    argocd.argoproj.io/secret-type: cluster
type: Opaque
data:
  name: ${B64_NAME}
  server: ${B64_SERVER}
  config: ${B64_CONFIG}
