name: Setup ArgoCD ReadOnly User

on:
  workflow_dispatch:

permissions:
  contents: read
  packages: write


jobs:
  setup-argocd-user:
    runs-on: ubuntu-latest

    env:
      AKS_CLUSTER_NAME: adaksargocd
      RESOURCE_GROUP: aniketdevops
      USERNAME: reader
      BCRYPT_PASSWORD: ${{ secrets.READER_BCRYPT_PASSWORD }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Get AKS Credentials
        run: az aks get-credentials --name $AKS_CLUSTER_NAME --resource-group $RESOURCE_GROUP --overwrite-existing

      - name: Patch argocd-cm to add reader account
        run: |
          kubectl -n argocd patch configmap argocd-cm --patch='{"data":{"accounts.reader": "apikey,login"}}'

      - name: Patch argocd-rbac-cm to add readonly policy
        run: |
          kubectl -n argocd patch configmap argocd-rbac-cm --patch='{"data":{"policy.default": "role:readonly"}}'

      - name: Restart ArgoCD Server Pod
        run: kubectl rollout restart deployment argocd-server -n argocd
