name: Setup ArgoCD ReadOnly User

on:
  workflow_dispatch:

permissions:
  contents: read
  packages: write


jobs:
  setup-argocd-user:
    runs-on: ubuntu-latest

    env:
      AKS_CLUSTER_NAME: adaksargocd
      RESOURCE_GROUP: aniketdevops
      USERNAME: reader
      BCRYPT_PASSWORD: ${{ secrets.READER_BCRYPT_PASSWORD }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Get AKS Credentials
        run: az aks get-credentials --name $AKS_CLUSTER_NAME --resource-group $RESOURCE_GROUP --overwrite-existing

      - name: Apply argocd-cm ConfigMap
        run: kubectl apply -f k8s/argocd/configmap.yaml

      - name: Apply argocd-rbac-cm ConfigMap
        run: kubectl apply -f k8s/argocd/reader-rbac-configmap.yaml

      - name: Patch ArgoCD Secret with User Password
        run: |
          kubectl patch secret argocd-secret -n argocd \
            --type merge \
            -p "{\"stringData\": {\"accounts.${USERNAME}.password\": \"${BCRYPT_PASSWORD}\"}}"

      - name: Restart ArgoCD Server Pod
        run: kubectl rollout restart deployment argocd-server -n argocd
