name: Enable Keda in Webapp Cluster

permissions:
  contents: read
  packages: write

on:
    workflow_dispatch:

jobs:
  deploy-argocd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
    
      - name: Setup kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'
  
      - name: Get AKS Credentials
        run: az aks get-credentials --name adaks  --overwrite-existing --resource-group aniketdevops

      - name: Enable Keda
        run: kubectl apply -f https://github.com/kedacore/keda/releases/download/v2.9.3/keda-2.9.3.yaml
