# name: Deploy to AKS

# on:
#   repository_dispatch:
#     types: [image-pushed]

# jobs:
#   deploy-to-aks:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3

#       - name: Azure Login
#         uses: azure/login@v1
#         with:
#           creds: ${{ secrets.AZURE_CREDENTIALS }}

#       - name: Configure kubectl
#         run: |
#           az aks get-credentials --resource-group aniketdevops --name adaks --overwrite-existing

#       - name: Deploy to AKS
#         run: |
#           kubectl apply -f kubernetes/namespace.yaml  # Optional if using a namespace
#           kubectl apply -f kubernetes/deployment.yaml
#           kubectl apply -f kubernetes/service.yaml
#           kubectl apply -f kubernetes/ingress.yaml

#       - name: Verify Deployment
#         run: |
#           kubectl get all -n aniketdevops-namespace  # If using a namespace

