name: Build and Push Docker Image

on:
    workflow_dispatch:
    push:
        paths:
            - 'app/**'
            - 'docker/**'
        branches:
            - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:

      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Azure Login to authenticate and get credentials
      - name: Azure Login
        uses: azure/login@v1
        with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Step 3: Get ACR credentials
      - name: Get ACR Credentials
        id: acr
        run: |
          ACR_USERNAME=$(az acr credential show --name adacr --query "username" -o tsv)
          ACR_PASSWORD=$(az acr credential show --name adacr --query "passwords[0].value" -o tsv)
          echo "ACR_USERNAME=$ACR_USERNAME" >> $GITHUB_ENV
          echo "ACR_PASSWORD=$ACR_PASSWORD" >> $GITHUB_ENV

      # Step 4: Log in to Azure Container Registry
      - name: Log in to ACR
        uses: docker/login-action@v2
        with:
          registry: adacr.azurecr.io
          username: ${{ env.ACR_USERNAME }}
          password: ${{ env.ACR_PASSWORD }}

      # Step 5: Generate Semantic Version for tagging
      - name: Generate SemVer
        run: echo "1.1.${{ github.run_number }}" > version.txt

      # Step 6: Build and Push Docker Image
      - name: Build and Push Docker Image
        run: |
          VERSION=$(cat version.txt)
          docker build -t adacr.azurecr.io/aniketdevops:$VERSION -t adacr.azurecr.io/aniketdevops:latest -f docker/Dockerfile .
          docker push adacr.azurecr.io/aniketdevops:$VERSION
          docker push adacr.azurecr.io/aniketdevops:latest

      # Step 7: Upload the version text file as an artifact (optional, for tracking purposes)
      - name: Upload image version
        uses: actions/upload-artifact@v4
        with:
          name: docker-version
          path: version.txt

      # Optional: Cache Docker layers for faster builds
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: ~/.cache/docker
          key: ${{ runner.os }}-docker-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-docker-
