name: Build and Push Docker Image

permissions:
  contents: read
  packages: write

on:
    workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Get ACR Credentials
        id: acr
        run: |
          ACR_USERNAME=$(az acr credential show --name adevopsacr --query "username" -o tsv)
          ACR_PASSWORD=$(az acr credential show --name adevopsacr --query "passwords[0].value" -o tsv)
          echo "ACR_USERNAME=$ACR_USERNAME" >> $GITHUB_ENV
          echo "ACR_PASSWORD=$ACR_PASSWORD" >> $GITHUB_ENV

      - name: Log in to ACR
        uses: docker/login-action@v2
        with:
          registry: adevopsacr.azurecr.io
          username: ${{ env.ACR_USERNAME }}
          password: ${{ env.ACR_PASSWORD }}

      # Generate Semantic Version for tagging
      - name: Generate SemVer
        run: echo "1.1.${{ github.run_number }}" > version.txt

      - name: Build and Push Docker Image
        run: |
          VERSION=$(cat version.txt)
          docker build -t adevopsacr.azurecr.io/aniketdevops:$VERSION -t adevopsacr.azurecr.io/aniketdevops:latest -f docker/Dockerfile .
          docker push adevopsacr.azurecr.io/aniketdevops:$VERSION
          docker push adevopsacr.azurecr.io/aniketdevops:latest

      # Upload the version text file as an artifact 
      - name: Upload image version
        uses: actions/upload-artifact@v4
        with:
          name: docker-version
          path: version.txt
